name: Deploy

on:
  push:
    branches:
      - main

jobs:
  client:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-wasm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-wasm-
      - uses: swiftwasm/swiftwasm-action@v5.5
        with:
          shell-action: carton bundle --product server-client
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Bundle
