name: Deploy

on:
  push:
    branches:
      - main

jobs:
  client:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-wasm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-wasm-
      - uses: swiftwasm/swiftwasm-action@v5.5
        with:
          shell-action: carton bundle --product server-client
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source-directory: './Bundle'
          destination-github-username: 'awelch6'
          destination-repository-name: 'awelch6.github.io'
          user-email: austinWelch276@icloud.com
          target-branch: main
